apiVersion: v1
kind: Service
metadata:
  labels:
    app: powerapp-mongodb-service
  name: powerapp-mongodb-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: powerapp-mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: powerapp-mongodb
  name: powerapp-mongodb
spec:
  serviceName: powerapp-mongodb-service 
  replicas: 1
  selector:
      matchLabels:
          app: powerapp-mongodb 
  template: 
    metadata:
      labels:
        app: powerapp-mongodb
      name: powerapp-mongodb
    spec:
      containers:
      - name: powerapp-mongo
        image: mongo:3.7.3
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name:  powerapp-db-volume
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
          labels:
            app: powerapp-db-volume
          name: powerapp-db-volume
      spec:
       accessModes: [ "ReadWriteOnce" ]
       resources:
           requests:
               storage: 1Gi
